### ISSUE TITLE
renderd throws reason: Postgis Plugin: bad connection error when rendering with render_list

### ISSUE THREAD

**Issue by a14stoner** [openstreetmap/mod_tile#467]
I set up mod_tile together with renderd. Rendering the map works well. When manually opening the map it renders non existing tiles fast an seamless. I already prerenderd my map from Z0 to Z17 (actually only half of Z17). 

When going to new spots on my map where the tiles are not prerenderd the tiles get generated without any problem. 

When trying to continue to render the whole Z17 (or Z18) i get the following error in the renderd.log:

```
** (process:1911): ERROR **: 14:25:34.040: failed to render TILE default 18 134760-134767 92840-92847

** (process:1911): ERROR **: 14:25:34.044:   reason: Postgis Plugin: bad connection

** (process:1911): ERROR **: 14:25:46.972: failed to render TILE default 17 70344-70351 45848-45855

** (process:1911): ERROR **: 14:25:46.972:   reason: Postgis Plugin: bad connection

** (process:1911): ERROR **: 14:25:46.972: failed to render TILE default 18 134760-134767 93080-93087

** (process:1911): ERROR **: 14:25:46.973:   reason: Postgis Plugin: bad connection

** (process:1911): ERROR **: 14:25:46.973: failed to render TILE default 18 134760-134767 93112-93119

** (process:1911): ERROR **: 14:25:46.972: failed to render TILE default 18 134760-134767 93000-93007

** (process:1911): ERROR **: 14:25:46.973:   reason: Postgis Plugin: bad connection

** (process:1911): ERROR **: 14:25:46.973:   reason: Postgis Plugin: bad connection

** (process:1911): ERROR **: 14:25:46.976: failed to render TILE default 18 134760-134767 93032-93039

** (process:1911): ERROR **: 14:25:46.976:   reason: Postgis Plugin: bad connection
```
since the rendering works when i manually go to new spots on the map i really dont know what the error is. 
also i dont know how to enable the debug logs on renderd... maybe some more information is logged there. 

here are my configurations: 

renderd.conf: 

```
[renderd]
pid_file=/var/run/renderd/renderd.pid
stats_file=/var/run/renderd/renderd.stats
socketname=/var/run/renderd/renderd.sock
num_threads=32
tile_dir=/usr/local/renderd/cache

[mapnik]
plugins_dir=/usr/lib/mapnik/3.1/input
font_dir=/usr/share/fonts
font_dir_recurse=true

[default]
URI=/tile/
XML=/usr/local/mapnik/openstreetmap-carto/CARTO_DE_AT_CH.xml
HOST=localhost
TILEDIR=/usr/local/renderd/cache

[topo]
URI=/topo/
XML=/usr/local/mapnik/OpenTopoMap/mapnik/opentopomap.xml
HOST=localhost
TILEDIR=/usr/local/renderd/cache

```
the start of the .mml file looks like this: 

```
# Various parts to be included later on
_parts:
  srid: &srid "3857"
  srs: &srs "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  world: &world
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  dach: &dach
    - 562163
    - 5733998
    - 1975921
    - 7424221
  # Extents are used for tilemill, and don't actually make it to the generated XML
  extents: &extents
    extent: *dach
    srs-name: *srid
    srs: *srs
  osm2pgsql: &osm2pgsql
    type: "postgis"
    geometry_field: "way"
    key_field: ""
    estimate_extend: "false"
    srid: *srid
    host: "POSTGIS"
    port: "5432"
    extent: *dach
    user: "gis"
    dbname: "DE_AT_CH_20240911"
    max_size: 100
    max_async_connection: 4
```
maybe if you have any idea what i did wrong... i would be very happy since I found nothing similar in any other issue (or I am just a bad googler ;) )
